# Generated by Django 4.2.3 on 2023-07-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('ideal_climate', models.CharField(max_length=50)),
                ('water_requirements', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=50)),
                ('growth_duration', models.CharField(max_length=50)),
            ],
        ),
    ]
