# Generated by Django 4.2.3 on 2023-07-30 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crop', '0001_initial'),
        ('User', '0001_initial'),
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crop.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
