# Generated by Django 4.2.3 on 2023-07-30 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('ideal_climate', models.CharField(max_length=100)),
                ('water_requirements', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('growth_duration', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.customer')),
            ],
        ),
    ]
